on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  test:

    runs-on: windows-latest

    steps:
    
    - name: Run PSScriptAnalyzer
      uses: microsoft/psscriptanalyzer-action@v1.0
      with:
          # Specifies the path to the scripts or module to be analyzed. Wildcard characters are supported.
          path: .\
          recurse: true 
          ignorePattern: "tests"
          output: results.sarif
    
    - name: Upload SARIF results file
      uses: github/codeql-action/upload-sarif@v1
      with:
          sarif_file: results.sarif